export enum ErrorCode {
  // Generic
  INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'ERR_VALIDATION_ERROR',
  BAD_REQUEST = 'ERR_BAD_REQUEST',
  UNAUTHORIZED = 'ERR_UNAUTHORIZED',
  FORBIDDEN = 'ERR_FORBIDDEN',
  NOT_FOUND = 'ERR_NOT_FOUND',
  CONFLICT = 'ERR_CONFLICT',
  RATE_LIMIT_EXCEEDED = 'ERR_RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE = 'ERR_SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT = 'ERR_GATEWAY_TIMEOUT',

  // Auth
  INVALID_CREDENTIALS = 'ERR_AUTH_INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'ERR_AUTH_TOKEN_EXPIRED',
  TOKEN_INVALID = 'ERR_AUTH_TOKEN_INVALID',
  ACCOUNT_LOCKED = 'ERR_AUTH_ACCOUNT_LOCKED',
  ACCOUNT_DISABLED = 'ERR_AUTH_ACCOUNT_DISABLED',
  MFA_REQUIRED = 'ERR_AUTH_MFA_REQUIRED',
  MFA_INVALID_CODE = 'ERR_AUTH_MFA_INVALID_CODE',
  PASSWORD_TOO_WEAK = 'ERR_AUTH_PASSWORD_TOO_WEAK',

  // Inventory
  INSUFFICIENT_STOCK = 'ERR_INVENTORY_INSUFFICIENT_STOCK',
  RESERVATION_EXPIRED = 'ERR_INVENTORY_RESERVATION_EXPIRED',
  WAREHOUSE_UNAVAILABLE = 'ERR_INVENTORY_WAREHOUSE_UNAVAILABLE',

  // Order & Saga
  ORDER_INVALID_STATE_TRANSITION = 'ERR_ORDER_INVALID_STATE_TRANSITION',
  ORDER_ALREADY_PAID = 'ERR_ORDER_ALREADY_PAID',
  ORDER_ALREADY_CANCELLED = 'ERR_ORDER_ALREADY_CANCELLED',
  SAGA_EXECUTION_FAILED = 'ERR_SAGA_EXECUTION_FAILED',
  SAGA_COMPENSATION_FAILED = 'ERR_SAGA_COMPENSATION_FAILED',

  // Payment
  PAYMENT_DECLINED = 'ERR_PAYMENT_DECLINED',
  PAYMENT_METHOD_INVALID = 'ERR_PAYMENT_METHOD_INVALID',
  GATEWAY_COMMUNICATION_ERROR = 'ERR_PAYMENT_GATEWAY_ERROR',
  LEDGER_UNBALANCED_ENTRY = 'ERR_PAYMENT_LEDGER_UNBALANCED',
  REFUND_EXCEEDS_ORIGINAL = 'ERR_PAYMENT_REFUND_EXCEEDS_ORIGINAL',

  // Fulfillment
  CARRIER_RATE_UNAVAILABLE = 'ERR_FULFILLMENT_CARRIER_RATE_UNAVAILABLE',
  ADDRESS_UNVERIFIED = 'ERR_FULFILLMENT_ADDRESS_UNVERIFIED',
  PACKAGE_OVERSIZED = 'ERR_FULFILLMENT_PACKAGE_OVERSIZED'
}
