export enum FulfillmentStatus {
  UNFULFILLED = 'UNFULFILLED',
  ALLOCATING = 'ALLOCATING',
  PICKING = 'PICKING',
  PACKED = 'PACKED',
  LABEL_GENERATED = 'LABEL_GENERATED',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  SHIPPED = 'SHIPPED',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  FAILED_ATTEMPT = 'FAILED_ATTEMPT',
  RETURNED_TO_SENDER = 'RETURNED_TO_SENDER',
  LOST_IN_TRANSIT = 'LOST_IN_TRANSIT'
}

export enum CarrierCode {
  FEDEX = 'FEDEX',
  UPS = 'UPS',
  DHL = 'DHL',
  USPS = 'USPS',
  INTERNAL_FLEET = 'INTERNAL_FLEET',
  MOCK_CARRIER = 'MOCK_CARRIER'
}
