export enum OrderStatus {
  DRAFT = 'DRAFT',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_AUTHORIZED = 'PAYMENT_AUTHORIZED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PROCESSING = 'PROCESSING',
  INVENTORY_RESERVED = 'INVENTORY_RESERVED',
  INVENTORY_ALLOCATION_FAILED = 'INVENTORY_ALLOCATION_FAILED',
  PACKED = 'PACKED',
  DISPATCHED = 'DISPATCHED',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  EXPIRED = 'EXPIRED'
}

export enum OrderCancellationReason {
  CUSTOMER_REQUEST = 'CUSTOMER_REQUEST',
  PAYMENT_DECLINED = 'PAYMENT_DECLINED',
  INVENTORY_OUT_OF_STOCK = 'INVENTORY_OUT_OF_STOCK',
  SUSPECTED_FRAUD = 'SUSPECTED_FRAUD',
  CARRIER_RESTRICTION = 'CARRIER_RESTRICTION',
  TIMEOUT_EXPIRED = 'TIMEOUT_EXPIRED',
  SYSTEM_ERROR = 'SYSTEM_ERROR'
}
