version: '3.8'

services:
  # Infrastructure Services
  postgres:
    image: postgres:16-alpine
    container_name: novacommerce-postgres
    environment:
      POSTGRES_USER: novacommerce_user
      POSTGRES_PASSWORD: local_development_password_only
      POSTGRES_DB: novacommerce_main
    ports:
      - "5432:5432"
    volumes:
      - ../migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novacommerce_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: novacommerce-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: novacommerce-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mailhog:
    image: mailhog/mailhog:latest
    container_name: novacommerce-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: novacommerce-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.4.0
    container_name: novacommerce-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
