apiVersion: v1
kind: Secret
metadata:
  name: novacommerce-secrets
  namespace: novacommerce
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_WITH_KMS_VAULT_ROTATED_KEY_IN_PRODUCTION"
  DB_PASSWORD: "REPLACE_WITH_MANAGED_SECRET_IN_PRODUCTION"
